NguyenVuLong_181212110/Models/Entities/HangHoa.cs
namespace NguyenVuLong_181212110.Models.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("HangHoa")]
    public partial class HangHoa
    {
        [Key]
        public int MaHang { get; set; }

        public int MaLoai { get; set; }

        [Required]
        [StringLength(50)]
        public string TenHang { get; set; }

        [Column(TypeName = "numeric")]
        public decimal? Gia { get; set; }

        [StringLength(100)]
        public string Anh { get; set; }

        public virtual LoaiHang LoaiHang { get; set; }
    }
}

NguyenVuLong_181212110/Models/Entities/LoaiHang.cs
namespace NguyenVuLong_181212110.Models.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("LoaiHang")]
    public partial class LoaiHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoaiHang()
        {
            HangHoas = new HashSet<HangHoa>();
        }

        [Key]
        public int MaLoai { get; set; }

        [Required]
        [StringLength(50)]
        public string TenLoai { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HangHoa> HangHoas { get; set; }
    }
}

NguyenVuLong_181212110/Models/Entities/NguyenVuLong_Context.cs
using System;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Linq;

namespace NguyenVuLong_181212110.Models.Entities
{
    public partial class NguyenVuLong_Context : DbContext
    {
        public NguyenVuLong_Context()
            : base("name=NguyenVuLong_Context")
        {
        }

        public virtual DbSet<HangHoa> HangHoas { get; set; }
        public virtual DbSet<LoaiHang> LoaiHangs { get; set; }
        public virtual DbSet<tblAccount> tblAccounts { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<HangHoa>()
                .Property(e => e.Gia)
                .HasPrecision(18, 0);

            modelBuilder.Entity<LoaiHang>()
                .HasMany(e => e.HangHoas)
                .WithRequired(e => e.LoaiHang)
                .WillCascadeOnDelete(false);

            modelBuilder.Entity<tblAccount>()
                .Property(e => e.Username)
                .IsFixedLength();

            modelBuilder.Entity<tblAccount>()
                .Property(e => e.Password)
                .IsFixedLength();
        }
    }
}

NguyenVuLong_181212110/Models/Entities/tblAccount.cs
namespace NguyenVuLong_181212110.Models.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("tblAccount")]
    public partial class tblAccount
    {
        [Key]
        public int Uid { get; set; }

        [StringLength(10)]
        public string Username { get; set; }

        [StringLength(10)]
        public string Password { get; set; }
    }
}

NguyenVuLong_181212110/Controllers/BaiThiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NguyenVuLong_181212110.Models.Entities;
namespace NguyenVuLong_181212110.Controllers
{
    public class BaiThiController : Controller
    {
        NguyenVuLong_Context db = new NguyenVuLong_Context();
        // GET: BaiThi
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult RenderNav()
        {
            List<LoaiHang> listLoaiHang = db.LoaiHangs.ToList();
            return PartialView("NguyenVuLong_Header",listLoaiHang);
        }
        public ActionResult RenderProduct()
        {
            List<HangHoa> listHangHoa = db.HangHoas.Where(h => h.Gia >= 100).ToList();
            return PartialView("NguyenVuLong_Main", listHangHoa);
        }
        public ActionResult LoadProductByCatID(int CatID)
        {
            List<HangHoa> listHangHoa = db.HangHoas.Where(h => h.MaLoai == CatID).ToList();
            return PartialView("NguyenVuLong_Main", listHangHoa);
        }
        public ActionResult LoadProductByName(String searchString)     
        {
            List<HangHoa> listHangHoa = db.HangHoas.ToList().FindAll(x => x.TenHang.ToLower().Contains(searchString.ToLower()));
            return PartialView("NguyenVuLong_Main", listHangHoa);
        } 
        public ActionResult Create()
        {
            ViewBag.MaLoai = new SelectList(db.LoaiHangs, "MaLoai", "TenLoai");
            return View();
        }
        [HttpPost]
        public ActionResult Create(HangHoa hanghoa)
        {
            db.HangHoas.Add(hanghoa);
            db.SaveChanges();
            return Redirect("Index");
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            var hh = db.HangHoas.ToList().Find(x => x.MaHang ==id);
            ViewBag.MaLoai = new SelectList(db.LoaiHangs, "MaLoai", "TenLoai");
            return View(hh);
        }
        [HttpPost]
        public ActionResult Edit(HangHoa hanghoa)
        {
            //db.HangHoas.Add(hanghoa);
            var hh = db.HangHoas.ToList().Find(x => x.MaHang == hanghoa.MaHang);
            hh.TenHang = hanghoa.TenHang;
            hh.MaLoai = hanghoa.MaLoai;
            hh.Gia = hanghoa.Gia;
            hh.Anh = hanghoa.Anh;
            db.SaveChanges();
            return Redirect("Index");
        }

        [HttpGet]
        public ActionResult Delete(int id) {

            var hh = db.HangHoas.ToList().Find(x => x.MaHang == id);
            ViewBag.MaLoai = new SelectList(db.LoaiHangs, "MaLoai", "TenLoai");
            return View(hh);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Deletee(int id)
        {
            var hh = db.HangHoas.ToList().Find(x => x.MaHang == id);
            db.HangHoas.Remove(hh);
            db.SaveChanges();
            ViewBag.MaLoai = new SelectList(db.LoaiHangs, "MaLoai", "TenLoai");
            return Redirect("Index");
        }

    }
}

NguyenVuLong_181212110/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NguyenVuLong_181212110.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

NguyenVuLong_181212110/Views/BaiThi/Create.cshtml
@model NguyenVuLong_181212110.Models.Entities.HangHoa
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/NguyenVuLong_Layout.cshtml";
}

<h2>Nguyễn Vũ Long</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Thêm hàng hoá mới</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.MaLoai, "MaLoai", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaLoai", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaLoai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenHang, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenHang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenHang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Anh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Anh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Anh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

NguyenVuLong_181212110/Views/BaiThi/Delete.cshtml
@model NguyenVuLong_181212110.Models.Entities.HangHoa

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/NguyenVuLong_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>HangHoa</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.LoaiHang.TenLoai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LoaiHang.TenLoai)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenHang)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenHang)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Anh)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Anh)
        </dd>

    </dl>

    @using (Html.BeginForm("Deletee", "BaiThi", FormMethod.Post)) {
        @Html.AntiForgeryToken()

<div class="form-actions no-color">
    <input type="hidden" value="@Model.MaHang" name="id" />
    <input type="submit" value="Delete" class="btn btn-default" /> |
    @Html.ActionLink("Back to List", "Index")
</div>
    }
</div>

NguyenVuLong_181212110/Views/BaiThi/Edit.cshtml
@model NguyenVuLong_181212110.Models.Entities.HangHoa

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/NguyenVuLong_Layout.cshtml";
}

<h2>Edit @Model.TenHang</h2>
<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>HangHoa</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaHang)

        <div class="form-group">
            @Html.LabelFor(model => model.MaLoai, "MaLoai", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MaLoai", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MaLoai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TenHang, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenHang, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenHang, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gia, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Anh, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Anh, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Anh, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

NguyenVuLong_181212110/Views/BaiThi/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/NguyenVuLong_Layout.cshtml";
}

<h2>Nguyễn Vũ Long</h2>

@Html.Action("RenderProduct", "BaiThi")

NguyenVuLong_181212110/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

NguyenVuLong_181212110/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

NguyenVuLong_181212110/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

NguyenVuLong_181212110/Views/Shared/NguyenVuLong_Footer.cshtml
<div class="footer">
    <div class="wrap">
        <div class="section group">
            <div class="col_1_of_4 span_1_of_4">
                <h4>Information</h4>
                <ul>
                    <li><a href="about.html">About Us</a></li>
                    <li><a href="contact.html">Customer Service</a></li>
                    <li><a href="#">Advanced Search</a></li>

                </ul>
            </div>
            <div class="col_1_of_4 span_1_of_4">
                <h4>Why buy from us</h4>
                <ul>
                    <li><a href="about.html">About Us</a></li>
                    <li><a href="contact.html">Customer Service</a></li>
                    <li><a href="#">Privacy Policy</a></li>

                </ul>
            </div>
            <div class="col_1_of_4 span_1_of_4">
                <h4>My account</h4>
                <ul>
                    <li><a href="contact.html">Sign In</a></li>
                    <li><a href="index.html">View Cart</a></li>
                    <li><a href="#">My Wishlist</a></li>

                </ul>
            </div>
            <div class="col_1_of_4 span_1_of_4">
                <h4>Contact</h4>
                <ul>
                    <li><span>+91-123-456789</span></li>
                    <li><span>+00-123-000000</span></li>
                </ul>
            </div>
        </div>
    </div>
</div>

NguyenVuLong_181212110/Views/Shared/NguyenVuLong_Header.cshtml
@model IEnumerable<NguyenVuLong_181212110.Models.Entities.LoaiHang>
<div class="header">
    <div class="header_top">
        <div class="logo">
            <a href="index.html"><img src="images/logo.png" alt="" /></a>
        </div>
        <div class="cart">
            <p>
                Welcome to our Online Store! <span>Cart:</span><div id="dd" class="wrapper-dropdown-2">
                    0 item(s) - $0.00
                    <ul class="dropdown">
                        <li>you have no items in your Shopping cart</li>
                    </ul>
                </div>
            </p>
        </div>
        <div class="clear"></div>
    </div>
    <div class="header_bottom">
        <div class="menu">
            <ul>
                <li class="active"><a>Nguyễn Vũ Long</a></li>
                @foreach (var l in Model)
            {
                <li id="@l.MaLoai"><a>@l.TenLoai</a></li>
            }
                <div class="clear"></div>
            </ul>
        </div>
        <div class="search_box">
            <form>
                <input type="text" id ="searchbox" value="Search" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search';}">
                <input type="button" value="" id="searchbtn" onclick="Onsearch()">
            </form>
        </div>
        <div class="clear"></div>
    </div>
</div>
<script>
    $("li").click(function (e) {
        var id = $(this).attr("id")
        $.ajax({
            url: "LoadProductByCatID",
            data: { CatID: id },
            success: function (response) {
                $("div.content").html(response)
            }
        });
    });

    function Onsearch() {
        searchstring = document.getElementById("searchbox").value
        console.log(searchstring)
        $.ajax({
            url: "LoadProductByName",
            data: { searchString: searchstring },
            success: function (response) {
                $("div.content").html(response)
                console.log(response)
            }
        });
    }
    
</script>

NguyenVuLong_181212110/Views/Shared/NguyenVuLong_Layout.cshtml
<!DOCTYPE HTML>
<head>
    <title>Free Home Shoppe Website Template | Home :: w3layouts</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/mycss")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/myscript")
    @Scripts.Render("~/bundles/bootstrap")
 
</head>
<body>
    <!-- Begin Wrap -->
    <div class="wrap">
        <!-- Begin Header -->
        @Html.Action("RenderNav", "BaiThi")
        <!-- End Header -->
        <!-- Begin Main -->
        @RenderBody()
        <!-- End Main -->
    </div>
    <!-- End Wrap -->
    <!-- Begin Footer -->
    @Html.Partial("NguyenVuLong_Footer")
    <!-- End Footer -->

    @RenderSection("scripts", required: false)

    <script type="text/javascript">
        $("#delete").on("click", function () {


        })
    </script>
</body>
</html>

NguyenVuLong_181212110/Views/Shared/NguyenVuLong_Main.cshtml
@model IEnumerable<NguyenVuLong_181212110.Models.Entities.HangHoa>
<div class="main">
    <div class="content">
        <!-- Begin New Product -->
        <div class="content_top">
            <div class="heading">
                <h3>Nguyễn Vũ Long</h3>
            </div>
            <div class="see">
                <p><a href="#">See all Products</a></p>
            </div>
            <div class="clear"></div>
        </div>
        <div class="section group">
            @foreach (var hh in Model)
            {
                <div class="grid_1_of_4 images_1_of_4">
                    <a href="preview.html"><img src="~/Content/images/@hh.Anh" alt="" /></a>
                    <h2>@hh.TenHang </h2>
                    <div class="price-details">
                        <div class="price-number">
                            <p><span class="rupees">@hh.Gia</span></p>
                        </div>
                        <div class="add-cart">
                            <h4><a href="/baithi/delete?id=@hh.MaHang" id="delete">delete</a></h4>

                        </div>
                        <div class="add-cart">
                            <h4><a href="/baithi/edit?id=@hh.MaHang" id="delete">Add to Cart</a></h4>

                        </div>

                        <div class="clear"></div>
                    </div>
                </div>
            }
        </div>
        <!-- End New Product -->
    </div>
</div>

NguyenVuLong_181212110/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>